Port to Python 3
sugarlabs/words-activity pull request #20
Opened 2019-12-12 13:29 UTC by Kiy4h

2019-12-12 13:45 UTC, tchx84 commented
I tested this, simply wrote "table" on the word field to translate it from English to Spanish and got the following error:

```
Traceback (most recent call last):
  File "/home/sugar/words-activity/wordsactivity.py", line 615, in __totranslate_activated_cb
    self._translate()
  File "/home/sugar/words-activity/wordsactivity.py", line 641, in _translate
    translations[i] = translations[i].decode()
AttributeError: 'str' object has no attribute 'decode'
```

2019-12-12 13:46 UTC, tchx84 commented on dictdlib.py
> +
A typo?

2019-12-12 13:49 UTC, tchx84 requested changes
Please test the activity as well.

2019-12-12 22:46 UTC, Kiy4h commented on dictdlib.py
> +
Whoops, fixed.

2019-12-12 22:48 UTC, Kiy4h commented
I forget to test after f3f2527, it won't happen again. It was now tested in a VM and running smoothly.

2019-12-13 04:13 UTC, quozl commented
Thanks.  Great progress.  Tests out fine for me.

However, you should have opened this pull request to merge into the _master_ branch.  I've taken your changes relative to @pro-panda's and pushed to _master_ along with my own changes.

2019-12-13 04:13 UTC, closed without merging

2019-12-13 04:18 UTC, Kiy4h commented
Whoops, sorry!

2019-12-13 04:18 UTC, Kiy4h commented
Whoops, sorry!

2019-12-13 04:18 UTC, Kiy4h commented
Whoops, sorry!

2019-12-13 04:18 UTC, Kiy4h commented
Whoops, sorry!

2019-12-13 04:21 UTC, quozl commented
No worries, I can git.  :grin: